<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Про нас',
    'Category' => 'Категорії',
    'Contact' => 'Контакт',
    'Go back' => 'Повернутися',
    'Home' => 'Головна',
    'Login' => 'Вхід',
    'Logout' => 'Вихід',
    'New by category {name}' => 'Новини в категорії «{name}»',
    'News' => 'Новини',
    'News in this category' => 'Новини по темі цієї категорії',
    'News with tag' => 'Новини на тему',
    'Online news' => 'Новини онлайн',
    'Page not found' => 'Сторінку не знайдено',
    'Signup' => 'Реєстрація',
    'Start the journey' => 'Почати подорож',
    'Subscribe to get the latest news' => 'Підпишіться, щоб отримувати найсвіжіші новини',
    'Tag' => 'Позначки',
    'You are on tags index page' => 'Весь перелік новин за темами',
    'New message after switched to db message source.' => '',
    'You {n,plural,
    offset:1
    =0{did not like this}
    =1{liked this}
    one{and one other person liked this}
    other{and # others liked this}
}' => 'Ви {n,plural,
    offset:1
    =0{ще не поставили лайк}
    =1{поставили лайк}
    one{и ще один поставили лайк}
    other{та # інших поставили лайк}
}',
    '{n,number} is spelled as {n,spellout}' => 'Число {n,number} прописом: {n, spellout}',
    'Default value for source language is English' => 'Англійська це значення для мови за замовчанням',
];
